### ISSUE TITLE
如何使用共享云端硬盘？

### ISSUE THREAD

**Issue by feilongproject** [donwa/goindex#117]
我想使用共享云端硬盘，而不是我的云端硬盘，请问怎么弄？多谢了

**Comment by dorothyturner** [comment]
代码11行左右有root参数，把自带的root值删除，填写共享盘id(https://drive.google.com/drive/u/0/folders/xxx，xxx就是共享盘id)

**Comment by useforaya** [comment]
@dorothyturner 谢谢，已经设置好了

**Comment by feilongproject** [comment]
> 代码11行左右有root参数，把自带的root值删除，填写共享盘id([https://drive.google.com/drive/u/0/folders/xxx，xxx就是共享盘id](https://drive.google.com/drive/u/0/folders/xxx%EF%BC%8Cxxx%E5%B0%B1%E6%98%AF%E5%85%B1%E4%BA%AB%E7%9B%98id))

多谢了，已经可以用了！
