### ISSUE TITLE
教育版 Google Drive 似乎無法使用

### ISSUE THREAD

**Issue by BirkhoffLee** [donwa/goindex#16]
.edu 結尾的無限容量 Google Drive 測試後網頁不顯示任何檔案

**Comment by xhwsd** [comment]
可以的，我的就是~

**Comment by BirkhoffLee** [comment]
@xhwsd 我是透過 README 的說明透過 rclone 進行使用，不過裡面沒有給 root_folder_id。請問你這邊是填什麼

**Comment by BirkhoffLee** [comment]
弄好了，不好意思打擾了。
