### ISSUE TITLE
Password protection issues

### ISSUE THREAD

**Issue by Mistereo** [donwa/goindex#37]
1. Passwords can still be accessed using: `/.PASSWORD` (or any other variation like `/.PassWord`), b/c search is case insensitive, eg: https://index.gd.workers.dev/test/.PASSWORD
2. Even if above is fixed, you still can access files by knowing their names, so brute force for common names is possible, eg: you can open https://index.gd.workers.dev/test/a/ and download https://index.gd.workers.dev/test/a/a.txt without entering password for https://index.gd.workers.dev/test.

**Comment by donwa** [comment]
Thank you.
1.Already fixed in version 1.0.3
2.There is no good way to traverse upwards for the time being. If this requirement is large, might consider rewriting the function code.

**Comment by donwa** [comment]
@Mistereo  Can you help me with the english documentation?

**Comment by Mistereo** [comment]
@donwa I would love to, but English is not my native language as well, your current readme looks great to me.
I also found another way to download ".password" file: https://index.gd.workers.dev/test/'%20or%20name%20=%20'.password
We definitely need to escape `'` from user input and maybe other symbols as well.

**Comment by donwa** [comment]
This way is really weird. There will be injection problems.
