### ISSUE TITLE
建议音频文件加预览

### ISSUE THREAD

**Issue by OctLan** [donwa/goindex#48]
音频文件加上<audio>标签预览

**Comment by OctLan** [comment]
https://gd.oct.workers.dev/%E5%85%89%E7%9B%98/%E5%B0%8F%E5%AD%A6%E8%8B%B1%E8%AF%AD%E4%B8%80%E5%B9%B4%E7%BA%A7%E4%B8%8A%EF%BC%88%E4%BA%BA%E6%95%99%E7%89%88%EF%BC%89%E7%AC%AC1%E7%89%87/   加入audio标签在线播放

**Comment by ATIAboo** [comment]
大佬 你这个预览咋实现的啊
