### ISSUE TITLE
目录点进去加载不出

### ISSUE THREAD

**Issue by Gigasnow** [donwa/goindex#58]
只有根目录能完整列举，点进任何目录都会一直转圈圈出不了文件

**Comment by hucstar** [comment]
咦，你关闭了这个issues，解决了吗？我也是这样啊！

**Comment by Gigasnow** [comment]
解决了，是我漏填了一个斜杠。严格按照教程步骤来就没问题了。

**Comment by hucstar** [comment]
是按第二种便捷方法来的吗？没有用到斜杠的地方啊？奇怪了……

**Comment by Gigasnow** [comment]
add route 里面，域名后加 /*
