### ISSUE TITLE
大佬 团队盘 需要其他设置吗? 测试安装好了,下载出现403,求帮助

### ISSUE THREAD

**Issue by logdns** [donwa/goindex#7]
大佬 团队盘 需要其他设置吗? 测试安装好了,下载出现403,求帮助
{
error: {
errors: [
{
domain: "global",
reason: "cannotDownloadAbusiveFile",
message: "This file has been identified as malware or spam and cannot be downloaded."
}
],
code: 403,
message: "This file has been identified as malware or spam and cannot be downloaded."
}
}

**Comment by donwa** [comment]
你的文件报病毒不让下载啊，不是很清楚吗？

**Comment by logdns** [comment]
好的 大佬 我上传了 bat 原来是监控到了

**Comment by logdns** [comment]
感谢大佬
