### ISSUE TITLE
子目录添加.password文件后，输入密码无法打开

### ISSUE THREAD

**Issue by iCirno** [donwa/goindex#93]
目录下添加.password后目录加密，该目录输入密码无法打开，重复跳输入密码框

**Comment by njzjz** [comment]
我发现了问题，原因是`.password`文件有个换行符`\n`。
https://github.com/donwa/goindex/blob/6f6e5067665969b695487a827d5b38f9bccbd647/index.js#L79
这行改为
```js
 if(password.replace("\n", "") != obj.password){ 
```
即可。

**Comment by iCirno** [comment]
> 
> 
> 我发现了问题，原因是`.password`文件有个换行符`\n`。
> 
> https://github.com/donwa/goindex/blob/6f6e5067665969b695487a827d5b38f9bccbd647/index.js#L79
> 
> 这行改为
> 
> ```js
>  if(password.replace("\n", "") != obj.password){ 
> ```
> 
> 即可。

dalao还是不行啊

**Comment by njzjz** [comment]
你可以在cloudflare的调试界面看一下他识别到的密码是什么

————————
Jinzhe Zeng
PhD student in Chemistry
Rutgers University

jinzhe.zeng@rutgers.edu
CV: https://njzjz.win/cv
